Tambah dan merubah tabel dan model
prasetyoadis/project-ck pull request #22
Opened 2024-08-18 03:09 UTC by tunetun123

beberapa perubahan struktur dan relasi tabel di bagian order, testimoni dan penambahan tabel dan model untuk template undangan.

2024-08-19 12:49 UTC, prasetyoadis requested changes
revisi yang ada, Terima Kasih

2024-08-19 12:49 UTC, prasetyoadis commented on database/migrations/2024_08_18_022846_create_template_undangan_table.php
> +            $table->string('category');
ini dipisah jadi tabel category

2024-08-19 12:49 UTC, prasetyoadis commented on database/migrations/2024_08_18_022846_create_template_undangan_table.php
> +        Schema::create('template_undangan', function (Blueprint $table) {
namanya kepanjangan, jadikan ke theme

2024-08-19 12:49 UTC, prasetyoadis commented on database/migrations/2024_07_23_044958_create_undangan_table.php
> +            $table->foreignId('template_undangan_id');
theme_id

2024-08-21 07:20 UTC, tunetun123 commented
tabel tamplate undangan diganti ke theme
tambah tabel category
buat model untuk theme dan category

2024-08-26 02:50 UTC, prasetyoadis approved these changes

2024-08-26 03:08 UTC, merged